services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: contact_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testing -d contact_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    image: prengineering/backend:latest
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://testing:testing@database:5432/contact_db
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: prengineering/frontend:latest
    expose:
      - "80"
    depends_on:
      - backend
volumes:
  postgres_data:
